spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 100Mb
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
  
logging:
  level:
    com.netflix: debug
