spring:
  application:
    name: microservice-gateway-zuul

server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    abc:       #abc 只要是唯一的
      path: /myusers-url/**
      serviceId: microservice-provider-user
  prefix: /simple
  strip-prefix: false    #默认为true http://localhost:8040/api/microservice-provider-user/simple/1正常访问
                        # false  不移除前缀，在调用user服务时： microservice-provider-user using LB returned Server: 192.168.0.110:7931 for request /simple/simple/1
                         #false http://localhost:8040/simple/microservice-provider-user/1  正常访问
  
logging:
  level:
    com.netflix: debug
